version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - condor-network

  frontend:
    build: ./condorai
    ports:
      - "3000:80"
    networks:
      - condor-network

networks:
  condor-network:
